kind: pipeline
name: photo-date-exif-repair
type: docker

trigger:
  branch:
    - master

steps:
  - name: build
    image: rust:1.66
    pull: if-not-exists
    commands:
    - cargo build
    depends_on: []

  - name: test
    image: rust:1.66
    pull: if-not-exists
    commands:
    - cargo test --verbose
    depends_on:
    - build

  - name: lint
    image: rust:1.66
    pull: if-not-exists
    commands:
    - rustup component add clippy
    - cargo clippy -- -D warnings
    depends_on:
    - build

  - name: fmt
    image: rust:1.66
    pull: if-not-exists
    commands:
    - rustup component add rustfmt
    - cargo fmt --all -- --check
    depends_on:
    - build
