kind: pipeline
name: photo-date-exif-repair
type: docker

trigger:
  branch:
    - master

steps:
  - name: build
    image: rust:1.66
    pull: if-not-exists
    commands:
    - cargo build

  - name: test
    image: rust:1.66
    pull: if-not-exists
    commands:
    - cargo test --verbose

  - name: lint
    image: rust:1.66
    pull: if-not-exists
    commands:
    - cargo clippy -- -D warnings

  - name: fmt
    image: rust:1.66
    pull: if-not-exists
    commands:
    - cargo fmt --all -- --check
